### ISSUE TITLE
Duplicate dependent packages

### ISSUE THREAD

**Issue by munechika-koyo** [cherab/imas#11]
Hi,
Currently, `cherab.imas` has dependencies of `raysect` and `cherab` but, I think we should have only the `cherab` dependency because `cherab` itself depends on `raysect` as well.
What do you think about it?

**Comment by vsnever** [comment]
Hi @munechika-koyo,
Currently, cherab-imas extends Raysect's functional framework and thus directly uses Raysect, so let's keep it as a dependency. We discussed this topic with @jacklovell here, https://github.com/cherab/solps/pull/74#discussion_r1734260714. I plan to move the grid interpolators and other Cython functions into the core Cherab module, as they are quite general. Then we might remove the explicit dependency on Raysect.

**Comment by munechika-koyo** [comment]
Thank you for answering my suggestion, @vsnever !
I understand your opinions and will close this issue.
